services:
  bds-postgres-db:
    image: 'postgres:15-alpine'
    container_name: bds-postgres-db
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      #PGDATA: '${POSTGRES_DATA_DIRECTORY}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${POSTGRES_USER}'
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      - './db_init/:/docker-entrypoint-initdb.d/'
      - './ssl_files/server.key:/etc/postgres/server.key'
      - './ssl_files/server.crt:/etc/postgres/server.crt'
      - './pg_hba.conf:/etc/postgres/pg_hba.conf'
    networks:
      - bds-project-net
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        chown postgres:root /etc/postgres/server.key &&
        chown postgres:root /etc/postgres/server.crt &&
        chown postgres:root /etc/postgres/pg_hba.conf &&
        chmod 600 /etc/postgres/server.key &&
        chmod 600 /etc/postgres/server.crt &&
        chmod 600 /etc/postgres/pg_hba.conf &&
        docker-entrypoint.sh postgres
        -c ssl=on
        -c ssl_cert_file=/etc/postgres/server.crt
        -c ssl_key_file=/etc/postgres/server.key
        -c hba_file=/etc/postgres/pg_hba.conf
    
  
  bds-pgadmin:
    image: 'dpage/pgadmin4:7.8'
    container_name: bds-pgadmin
    restart: unless-stopped
    ports:
      - '127.0.0.1:80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    depends_on:
      bds-postgres-db:
        condition: service_healthy
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
      - './pgadmin_conf/servers.json:/pgadmin4/servers.json'
      - './pgadmin_conf/pgpass:/pgadmin4/pgpass'
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        mkdir -pm 700 /var/lib/pgadmin/storage && 
        mkdir -pm 700 /var/lib/pgadmin/storage/${PGADMIN_USER_DIRECTORY} && 
        chown -R pgadmin:root /var/lib/pgadmin/storage/${PGADMIN_USER_DIRECTORY} &&
        cp /pgadmin4/pgpass /var/lib/pgadmin/storage/${PGADMIN_USER_DIRECTORY}/pgpassfile &&
        chmod 600 /var/lib/pgadmin/storage/${PGADMIN_USER_DIRECTORY}/pgpassfile &&
        /entrypoint.sh
    networks:
      - bds-project-net
  
  bds-flyway:
    image: 'flyway/flyway:9.22-alpine'
    container_name: bds-flyway
    restart: unless-stopped
    depends_on:
      bds-postgres-db:
        condition: service_healthy
    command: '-configFiles=/flyway/conf/flyway.conf migrate'
    volumes:
      - './flyway:/flyway/sql'
      - './flyway.conf:/flyway/conf/flyway.conf'
    networks:
      - bds-project-net
volumes:
  postgres-data:
    name: postgres-data
  pgadmin-data:
    name: pgadmin-data
networks:
  bds-project-net:
    name: bds-project-net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'br-bds-project'